### ISSUE TITLE
app:repeatItems="false" causes crash

### ISSUE THREAD

**Issue by hrstrand** [LukeDeighton/WheelView#10]
When setting repeatItems to false, I get the below exception. Bug ? Or did I setup something wrong.
I use the sample as a base, with same adapter and 40 items

E/AndroidRuntime( 5803): java.lang.ArrayIndexOutOfBoundsException: length=40; index=-10
E/AndroidRuntime( 5803): 	at com.lukedeighton.wheelview.WheelView.onDraw(WheelView.java:971)
E/AndroidRuntime( 5803): 	at android.view.View.draw(View.java:15231)
E/AndroidRuntime( 5803): 	at android.view.View.updateDisplayListIfDirty(View.java:14167)
E/AndroidRuntime( 5803): 	at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime( 5803): 	at android.view.View.draw(View.java:14959)
E/AndroidRuntime( 5803): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime( 5803): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime( 5803): 	at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime( 5803): 	at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime( 5803): 	at android.view.View.draw(View.java:14959)
E/AndroidRuntime( 5803): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3405)

**Comment by LukeDeighton** [comment]
I'll look into this, please can you paste your xml tag for <WheelView> so I can see what settings you are using ?

**Comment by hrstrand** [comment]
Luke - thanks. Here is the XML used.   

 <com.lukedeighton.wheelview.WheelView
        android:id="@+id/wheelview"
        android:layout_width="match_parent"
        android:layout_height="200dip"
        app:wheelColor="@color/greydark"
        app:rotatableWheelDrawable="true"
        app:selectionAngle="90.0"
        app:wheelPosition="bottom"
        app:wheelOffsetY="160dp"
        app:repeatItems="false"
        app:emptyItemColor="@color/greydark"
        app:emptyItemDrawable="@drawable/ic_viewfinder_overflow"
        app:wheelRadius="276dp"
        app:wheelItemCount="20"
        app:wheelPadding="13dp"
        app:wheelItemRadius="33dp"/>

**Comment by LukeDeighton** [comment]
@hrstrand I've fixed the crashing on repeatItems=false. 

If it doesn't work the way you expect let me know.
