### ISSUE TITLE
how to refresh wheelview by using adapter as we do in listview with notifyDataSetChanged ??

### ISSUE THREAD

**Issue by erumhannan** [LukeDeighton/WheelView#11]
i m trying to use this  code https://www.dropbox.com/s/ir4xkkbxz88lgp6/SampleWheelView.zip?dl=0  with little changes inside click listener 

wheelView.setOnWheelItemClickListener(new OnWheelItemClickListener() {
			@Override
			public void onWheelItemClick(WheelView parent, int position,boolean isSelected) {
				Toast.makeText(getApplicationContext(),String.format("%d", position), Toast.LENGTH_SHORT).show();
				mModelList = new ArrayList<Model>();
				Model model = new Model("5", "Text One");
				mModelList.add(model);
				Model model1 = new Model("5", "+");
				mModelList.add(model1);
				Model model2 = new Model("7", "This Two");
				mModelList.add(model2);
				Model model3 = new Model("8", "+");
				mModelList.add(model3);
				Model model4 = new Model("9", "Text Three");
				mModelList.add(model4);
				Model model5 = new Model("10", "Text Three");
				mModelList.add(model5);
				wheelView.setWheelItemCount(mModelList.size());
				wheelView.setAdapter(new MaterialColorAdapter(getApplicationContext(),mModelList));
				
			}
		});

but this is throwing error  related to arraylist size  why this is happening inside this library while aray i m going to provide to an array adapter is already have updated size  @LukeDeighton  @iffa

**Comment by LukeDeighton** [comment]
@erumhannan I haven't got a good way to refresh the data / Drawables yet, even though it looks like an Adapter it doesn't behave like the Android Adapters. I will look into this.

**Comment by LukeDeighton** [comment]
@erumhannan I haven't kept the API that similar to using notifyDataSetChanged because unlike Views, the Drawables don't need recycling. You have two options for refreshing the wheel items. Either create and set a new adapter, or if you need to only change one particular position you can use a new method `invalidateWheelItemDrawable`.
