### ISSUE TITLE
How to  get color code on wheel item selected listener called ? 

### ISSUE THREAD

**Issue by erumhannan** [LukeDeighton/WheelView#12]
i m using this code to create oval with different random colors : here is the code for create oval 

private Drawable createOvalDrawable(String text) {
			Log.d(TAG,"createOvalDrawable called:");
			ShapeDrawable shapeDrawable = new ShapeDrawable(new OvalShape());
			if (text.equals("+")) {
				shapeDrawable.getPaint().setColor(Color.YELLOW);
			} else {
				
				int colorRandId = Util.randInt(0,(colors.length-1));
				if(colorRandId < colors.length)
				{
				Log.d(TAG,"colors array:"+colors[colorRandId]);		
				shapeDrawable.getPaint().setColor(colors[colorRandId]);
				}
				
			}
			return shapeDrawable;
		}

now what i want is : once i select any wheel item that is : 
wheelView
		.setOnWheelItemSelectedListener(new WheelView.OnWheelItemSelectListener() {
			@Override
			public void onWheelItemSelected(WheelView parent,
					int position) {
				
				Log.d(TAG," *** setOnWheelItemSelectedListener:***"+position);	
			}
		});

then inside this method how can i get color that in which color this oval drawable has been created @LukeDeighton

**Comment by LukeDeighton** [comment]
@erumhannan I have added a Drawable parameter to the `onWheelItemSelectListener` Interface. And a method for getting the Drawable `getWheelItemDrawable`.

From here you can downcast to get the color
