### ISSUE TITLE
layout size cannot be set the layout is taking half of the screen

### ISSUE THREAD

**Issue by athulcek** [LukeDeighton/WheelView#13]
i used with this property bt i was not able to resize the height of the whole view 

             android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#fff"
            app:repeatItems="true"
            app:rotatableWheelDrawable="true"
            app:selectionAngle="90.0"
            app:selectionPadding="4dp"
            app:wheelColor="#fff"
            app:wheelItemCount="10"
            app:wheelItemRadius="40dp"
            app:wheelPadding="13dp"
            app:wheelPosition="bottom"
            app:wheelRadius="276dp"

**Comment by LukeDeighton** [comment]
I've added view measurements now so using "wrap_content" should work on the latest commit. Try it and let me know if it solves your problem.
