### ISSUE TITLE
How can i display images from internet? use glide or picasso.

### ISSUE THREAD

**Issue by hellsam** [LukeDeighton/WheelView#15]
I want to display some images from internet into WheelView, i use glide and picasso, how should i do ?

**Comment by LukeDeighton** [comment]
It's possible but not easy at the moment. Ideally instead of having Drawables for WheelItems they can be Views. Similar to #4. 

For now you will need to create BitmapDrawable's from the downloaded images and either provide a new adapter each time or invalidate the drawables on download. see `invalidateWheelItemDrawable`. 

I know Picasso has a Target API so that it doesn't need to be downloaded directly into a View.

**Comment by hellsam** [comment]
Thank you very much for your answer. I know how to implement.

**Comment by juanCure** [comment]
Hi  @LukeDeighton, I am using your code in my project. Well i achieved add images from Web into Wheelview returning a BitmapDrawable into the getDrawable method in my Adapter for the Wheelview and even I occupied and Asynctask for the downloading of the images from Web, however when I run the project when i rotate the wheelview, its slow and freeze and in the logcat show the message "Skipped X frames - too much work inside the main thread". I look at  @hellsam has asked you about how add images from web into the wheelview using glide or Picasson, and you have answered that even He might use  Picasso for load the images however I don't understand how. I hope you could tell more suggestions for improvement it, and I'm sorry for my writting but english is not my native language.

**Comment by omidraha** [comment]
Sample code:

```
wheelView = view.findViewById(R.id.home_wheel_view);
String url = "https://secure.gravatar.com/avatar/7ca69e0beac2631b08529e01a36df587.jpg?s=150&d=mm&r=g";


Target target = new Target() {
	@Override
	public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
		Drawable drawable = new BitmapDrawable(getResources(), bitmap);
		wheelView.setWheelDrawable(drawable);
	}

	@Override
	public void onBitmapFailed(Exception e, Drawable errorDrawable) {

	}

	@Override
	public void onPrepareLoad(Drawable placeHolderDrawable) {

	}
};

Picasso.get().load(url).into(target);

```

**Comment by orcunorcun** [comment]
How can I use it for items? I want to show 6 image from internet with picasso. But your code just set background of WheelView. :/

**Comment by youssefwagih** [comment]
any sample please for loading URL for items in wheelview
