### ISSUE TITLE
how to set wheel view current position ?

### ISSUE THREAD

**Issue by erumhannan** [LukeDeighton/WheelView#17]
i m trying to set currnet position of wheelview same as index we set in listview ..... for this i m doing this ... but i  m not getting my desired result .. lets say i  have passed arraylist to settext in wheelview and i m setting selected position to 1 ..... but i m not getting  my desired result ? 
wheelView.setSelectedPosition(position);

wheelView.setWheelItemCount(3);
		wheelView.layoutWheelItems();
		wheelView.invalidate();
		wheelView.invalidateWheelItemDrawables();
	
		MaterialColorAdapter mat = new MaterialColorAdapter(context, groupList,false);
		wheelView.setAdapter(mat);

here is my adapter class : 

static class MaterialColorAdapter extends WheelArrayAdapter<Groups> {
		private Context mContext;
		List<Groups> grpList;
		boolean drawInnerText = false;

		MaterialColorAdapter(Context mContext,List<Groups> entries,boolean drawInnerText) {
			super(entries);
			//Log.d(TAG,"MaterialColorAdapter called");
			this.mContext = mContext;
			grpList = new ArrayList<Groups>();
			grpList = entries;
			Log.d(TAG, "MaterialColorAdapter:" + grpList.size());
			this.drawInnerText = drawInnerText;
		}

		@Override
		public Drawable getDrawable(int position) {

			Log.d(TAG, "getDrawable called for position:"+position);
			
			Log.d(TAG,"grpList.get(position).getTitle:"+grpList.get(position).getGroupTitle());
			Log.d(TAG,"grpList.get(position).getColor():"+grpList.get(position).getColor());
			Log.d(TAG,"grpList.get(position).isDefault:"+grpList.get(position).isDefault());
			Drawable mDrawable = createOvalDrawable(grpList.get(position)
					.getGroupTitle(),grpList.get(position).getColor());
			/*TextDrawableTop textDrawable = new TextDrawableTop(grpList.get(
					position).getGroupTitle());*/
			TextDrawableTop textDrawable;
			if(grpList.get(position).isDefault())
			{
				Log.d(TAG, "grpList.get(position).isDefault() if:"+grpList.get(position).isDefault());
				textDrawable = new TextDrawableTop(grpList.get(
						position).getGroupTitle()+" Default");
				textDrawable.setColor(Color.parseColor("#f0bd5b"));
			}
			else
			{
				Log.d(TAG, "grpList.get(position).isDefault() else:"+grpList.get(position).isDefault());
				textDrawable = new TextDrawableTop(grpList.get(
						position).getGroupTitle());
				textDrawable.setColor(mContext.getResources().getColor(
					android.R.color.white));
			}
			
			
			textDrawable.setTextSize(32f);
			
			if(grpList.get(position).isDefault())
			{
				Log.d(TAG, "grpList.get(position).isDefault() if:"+grpList.get(position).isDefault());
				textDrawable.setColor(Color.parseColor("#f0bd5b"));
			}
			else
			{
				Log.d(TAG, "grpList.get(position).isDefault() else:"+grpList.get(position).isDefault());
				textDrawable.setColor(mContext.getResources().getColor(
					android.R.color.white));
			}
			Drawable[] drawable;
			if(drawInnerText)
			{
				//Log.d(TAG,">drawInnerText>"+drawInnerText);
				TextDrawableCenter textDrawableCenter = new TextDrawableCenter("Save changes");
			    textDrawableCenter.setTextSize(15f);			    textDrawableCenter.setColor(mContext.getResources().getColor(android.R.color.white));
			    drawable = new Drawable[] { textDrawable, mDrawable,textDrawableCenter };
			}
			else
			{
			drawable = new Drawable[] { textDrawable, mDrawable };
			}
textDrawableCenter.setColor(mContext.getResources().getColor(android.R.color.holo_red_light));
			LayerDrawable layerDrawable = new LayerDrawable(drawable);
			return layerDrawable;
		}

		private Drawable createOvalDrawable(String text,int color) {
			Log.d(TAG, "createOvalDrawable called:");
			ShapeDrawable shapeDrawable = new ShapeDrawable(new OvalShape());
                     shapeDrawable.getPaint().setColor(Color.parseColor(Util.getGroupColor(color)));
			return shapeDrawable;
		}
	}

i m setting wheelView.setSelectedPosition(1); so it should select the item at index1 but this is not happening

**Comment by erumhannan** [comment]
@LukeDeighton   kindly look into this issue

**Comment by LukeDeighton** [comment]
@erumhannan I'll look into it this weekend when I have time.

**Comment by LukeDeighton** [comment]
@erumhannan update to the latest and try `wheelview.setSelected(position)` - let me know if this is what you intended to happen? (I haven't uploaded to maven yet) so you will have to pull locally
