### ISSUE TITLE
Crashes when I directly return a drawable in the getDrawable()

### ISSUE THREAD

**Issue by codingant007** [LukeDeighton/WheelView#18]
I write this in the mainActiviy where the wheel is created

<pre><code>
wheelView.setAdapter(new WheelAdapter() {
            @Override
            public Drawable getDrawable(int position) {
                return getResources().getDrawable(R.drawable.images)
}
@Override
public int getCount() {
          return 10;
            }
});
</code></pre>

It looks stable when left stationary but as soon as I try to rotate it, crashes

Please do correct me if this is not the way the the adapter is expected to be created

**Comment by LukeDeighton** [comment]
Can you post your stack trace please? I tried your code and it works. Must be something else causing it to crash

**Comment by codingant007** [comment]
It was due to error in my `OnWheelItemSelected` handler. Whenever I rotate a new Item is selected and crashes. No problem with the library itself.
Thank you for your time.
