### ISSUE TITLE
Set background of the wheelView as an image

### ISSUE THREAD

**Issue by codingant007** [LukeDeighton/WheelView#19]
Is there a way to set the background of the wheel view element as an image?
As we can use `android:background = "@drawable/imageResource"` for listView

**Comment by LukeDeighton** [comment]
Try `wheelview.setWheelDrawable` can take a resource id. Is this what you mean?

**Comment by codingant007** [comment]
I am not sure what `wheelview.setWheelDrawable` does but app crashes when I do it in `onCreate` of the activity. What I was looking for is to have an image view at the center of the wheel.

**Comment by LukeDeighton** [comment]
WheelDrawable does place an image at the center of the wheel.

```java
wheelView.setWheelDrawable(new BitmapDrawable(getResources(), BitmapFactory.decodeResource(getResources(), R.drawable.ic_launcher)));```

works without crashing for me. Maybe post a stack trace?
