### ISSUE TITLE
getMaterialColors issue + fix

### ISSUE THREAD

**Issue by AwaisKing** [LukeDeighton/WheelView#29]
The issue is in `getMaterialColors` function, after *LogCat-ing* **field.getName()**, it shows **$change** field 2 times, then other color names

So I added **try {}** before `String fieldName = field.getName();` and it worked

------------------------
## fix:

    private static HashMap<String, Integer> getMaterialColors(Context context) {
        Field[] fields = R.color.class.getFields();
        HashMap<String, Integer> materialHashMap = new HashMap<String, Integer>(fields.length);
        for(Field field : fields) {
            try {
                String fieldName = field.getName(); //prone to errors but okay for a sample!
                Log.d("AWAISKING_APP", "" + field.getName());
                if (fieldName.startsWith("abc") || fieldName.startsWith("material")) continue;

                try {
                    int resId = field.getInt(null);
                    materialHashMap.put(fieldName, context.getResources().getColor(resId));
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            } catch (Exception ex){}
        }

        return materialHashMap;
    }

**Comment by LukeDeighton** [comment]
@AwaisKing thanks, I've fixed this with #31
