### ISSUE TITLE
CUSTOM PNGS OR IMAGES FOR WHEELVIEW ITEMS INSTEAD OF TEXT

### ISSUE THREAD

**Issue by sivaskvs** [LukeDeighton/WheelView#44]
How can i add custom images in background of each item in wheelview instead of texts like 1,2,3.
![untitled](https://cloud.githubusercontent.com/assets/13255270/23712059/b0381a0a-0447-11e7-98d6-e170087fc6be.png)
how to add png images instead of text like 1,2,3 in the above image.

**Comment by LukeDeighton** [comment]
The wheel items are drawables, so anything you can do with drawables can be put here including https://developer.android.com/reference/android/graphics/drawable/BitmapDrawable.html

**Comment by omidraha** [comment]
Is there a sample code for that?
