### ISSUE TITLE
selected items color?

### ISSUE THREAD

**Issue by Swisyn** [LukeDeighton/WheelView#6]
Thank you for this amazing lib!

I was trying to write a game with this lib, but the problem is that I couldn't find anything about changing selected item's color. Is there something like this or do i just implement myself?

**Comment by LukeDeighton** [comment]
There isn't anything built in to handle that since the selected Drawable might not have colour (BitmapDrawable etc.)

I don't have a good way to refresh Drawables at the moment but you could keep a reference to each Drawable in your Adapter getDrawable() method then change the colour in OnWheelItemSelectListener.

**Comment by Swisyn** [comment]
Yes, I've tried to change selecteditem's color, but nothing happens.

the class is; http://codepaste.net/8bxfse
and the layout has the only wheelview; http://codepaste.net/zfgmuu

Where am i doing it wrong?

Thanks for the response by the way.

**Comment by LukeDeighton** [comment]
Are you trying to change the selection colour or the colour of the item?

If you wanted the items colour to change do something like this:

```
final ShapeDrawable[] drawables = new ShapeDrawable[letters.length];
        wheelView.setAdapter(new WheelAdapter() {
            @Override
            public Drawable getDrawable(int position) {
                Drawable[] drawable = new Drawable[]{
                        drawables[position] = (ShapeDrawable) createOvalDrawable(getResources().getColor(R.color.red_500)),
                        new TextDrawable(letters[position])
                };
                return new LayerDrawable(drawable);
            }

            @Override
            public int getCount() {
                return letters.length;
            }
        });

        wheelView.setOnWheelItemSelectedListener(new WheelView.OnWheelItemSelectListener() {
            @Override
            public void onWheelItemSelected(WheelView parent, int position) {
                parent.setSelectionDrawable(getNewDrawable(position));
                drawables[position].getPaint().setColor(Color.BLUE);
            }
        });
```

**Comment by Swisyn** [comment]
Thank you so much, this was exactly what i want. Finally i've finished the game with your greatest help :)
